package com.soulmate.model.test2;

import com.soulmate.model.test2.base.BaseAdminUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUsers extends BaseAdminUsers<AdminUsers> {
	public static final AdminUsers dao = new AdminUsers().dao();
}

