package com.soulmate.model.test2.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminUsers<M extends BaseAdminUsers<M>> extends Model<M> implements IBean {

	public M setAdminUserId(java.lang.Integer adminUserId) {
		set("admin_user_id", adminUserId);
		return (M)this;
	}
	
	public java.lang.Integer getAdminUserId() {
		return getInt("admin_user_id");
	}
	
	public M setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
		return (M)this;
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public M setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
		return (M)this;
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}
	
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public M setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
		return (M)this;
	}
	
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}
	
	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}
	
	public java.util.Date getLastLoginTime() {
		return getDate("last_login_time");
	}
	
	public M setLoginTimes(java.lang.Integer loginTimes) {
		set("login_times", loginTimes);
		return (M)this;
	}
	
	public java.lang.Integer getLoginTimes() {
		return getInt("login_times");
	}
	
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public M setQiYeWechatUserId(java.lang.String qiYeWechatUserId) {
		set("qi_ye_wechat_user_id", qiYeWechatUserId);
		return (M)this;
	}
	
	public java.lang.String getQiYeWechatUserId() {
		return getStr("qi_ye_wechat_user_id");
	}
	
	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}
	
}

